version: '3.7'

networks:
  ${SC_NETWORK_NAME}:
    name: ${SC_NETWORK_NAME}
    external: true

services:

  visualizer:
    image: dockersamples/visualizer
    volumes:
      - ${SC_PATH_SCRIPTS}:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ${SC_NETWORK_NAME}:
        aliases:
          - visualizer
    ports:
      - ${SC_METRICS_VISUALIZER}:8080
    deploy:
      replicas: 1
      placement:
        constraints: [ node.hostname == ${SC_ORG1_P1_WORKER} ]
