version: '3.7'

networks:
  ${SC_NETWORK_NAME}:
    name: ${SC_NETWORK_NAME}

services:

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:${SC_VERSION_FABRIC}
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=${SC_FABRIC_LOGLEVEL}
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - ${SC_PATH_ORGS}:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
        - ${SC_PATH_SCRIPTS}:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ${SC_PATH_CONF}/peercfg:/etc/hyperledger/peercfg
    depends_on:
      - ${SC_ORG1_P1_FQDN}
      - ${SC_ORG2_P1_FQDN}
    etworks:
      - ${SC_NETWORK_NAME}
