global:
  scrape_interval: 1s
  external_labels:
    monitor: "devopsage-monitor"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "${SC_ORDERER1_O1_FQDN}"
    static_configs:
      - targets: ["${SC_ORDERER1_O1_FQDN}:${SC_ORDERER1_O1_OPPORT}"]
  - job_name: "${SC_ORG1_P1_FQDN}"
    static_configs:
      - targets: ["${SC_ORG1_P1_FQDN}:${SC_ORG1_P1_OPPORT}"]
  - job_name: "${SC_ORG1_P2_FQDN}"
    static_configs:
      - targets: ["${SC_ORG1_P2_FQDN}:${SC_ORG1_P2_OPPORT}"]
  - job_name: "${SC_ORG2_P1_FQDN}"
    static_configs:
      - targets: ["${SC_ORG2_P1_FQDN}:${SC_ORG2_P1_OPPORT}"]
  - job_name: "${SC_ORG2_P2_FQDN}"
    static_configs:
      - targets: ["${SC_ORG2_P2_FQDN}:${SC_ORG2_P2_OPPORT}"]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]
  - job_name: node
    static_configs:
      - targets: ["node-exporter:9100"]
