#
# Copyright TE-FOOD International Corp., All Rights Reserved.
#

version: '3'

networks:
    swarmnet:
        external:
            name: ${NETWORK}

services:

    kafka1:
        image: hyperledger/fabric-kafka:$IMAGE_TAG_3RDP
        hostname: kafka1.${NETWORK}.foodchain.te-food.com
        networks:
            swarmnet:
                aliases:
                    - kafka1.${NETWORK}.foodchain.te-food.com
        volumes:
            - ${DATA}/orderer/kafka1:/tmp/kafka-logs
        environment:
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${NETWORK}
            - KAFKA_BROKER_ID=0
            - KAFKA_MESSAGE_MAX_BYTES=103809024
            - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - KAFKA_MIN_INSYNC_REPLICAS=2
            - KAFKA_DEFAULT_REPLICATION_FACTOR=3
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
        deploy:                                                                                                                                                                                                
            replicas: 1
            placement:
                constraints: [node.hostname == $SWARM_MANAGER]
            restart_policy:
                condition: any
                delay: 5s

    kafka2:
        image: hyperledger/fabric-kafka:$IMAGE_TAG_3RDP
        hostname: kafka2.${NETWORK}.foodchain.te-food.com
        networks:
            swarmnet:
                aliases:
                    - kafka2.${NETWORK}.foodchain.te-food.com
        volumes:
            - ${DATA}/orderer/kafka2:/tmp/kafka-logs
        environment:
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${NETWORK}
            - KAFKA_BROKER_ID=1
            - KAFKA_MESSAGE_MAX_BYTES=103809024
            - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - KAFKA_MIN_INSYNC_REPLICAS=2
            - KAFKA_DEFAULT_REPLICATION_FACTOR=3
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
        deploy:    
            replicas: 1
            placement:
                constraints: [node.hostname == $SWARM_MANAGER]
            restart_policy:
                condition: any 
                delay: 5s

    kafka3:
        image: hyperledger/fabric-kafka:$IMAGE_TAG_3RDP
        hostname: kafka3.${NETWORK}.foodchain.te-food.com
        networks:
            swarmnet:
                aliases:
                    - kafka3.${NETWORK}.foodchain.te-food.com
        volumes:
            - ${DATA}/orderer/kafka3:/tmp/kafka-logs
        environment:
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${NETWORK}
            - KAFKA_BROKER_ID=2
            - KAFKA_MESSAGE_MAX_BYTES=103809024
            - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - KAFKA_MIN_INSYNC_REPLICAS=2
            - KAFKA_DEFAULT_REPLICATION_FACTOR=3
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
        deploy:    
            replicas: 1
            placement:
                constraints: [node.hostname == $SWARM_MANAGER]
            restart_policy:
                condition: any 
                delay: 5s

    kafka4:
        image: hyperledger/fabric-kafka:$IMAGE_TAG_3RDP
        hostname: kafka4.${NETWORK}.foodchain.te-food.com
        networks:
            swarmnet:
                aliases:
                    - kafka4.${NETWORK}.foodchain.te-food.com
        volumes:
            - ${DATA}/orderer/kafka4:/tmp/kafka-logs
        environment:
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${NETWORK}
            - KAFKA_BROKER_ID=3
            - KAFKA_MESSAGE_MAX_BYTES=103809024
            - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - KAFKA_MIN_INSYNC_REPLICAS=2
            - KAFKA_DEFAULT_REPLICATION_FACTOR=3
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
        deploy:    
            replicas: 1
            placement:
                constraints: [node.hostname == $SWARM_MANAGER]
            restart_policy:
                condition: any 
                delay: 5s

