#
# Copyright TE-FOOD International Corp., All Rights Reserved.
#

version: '3'

networks:
    swarmnet:
        external:
            name: ${NETWORK}

services:

    #
    # zookeepers
    #

    zookeeper1:
        image: hyperledger/fabric-zookeeper:$IMAGE_TAG_3RDP
        hostname: zookeeper1
        networks:
            swarmnet:
                aliases:
                    - zookeeper1.${NETWORK}.foodchain.te-food.com
        volumes:
            - ${DATA}/orderer/zookeeper1/data:/data
            - ${DATA}/orderer/zookeeper1/datalog:/datalog
        environment:
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${NETWORK}
            - ZOO_MY_ID=1
            - ZOO_SERVERS=server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
        deploy:                                                                                                                                                                                                
            replicas: 1
            placement:
                constraints: [node.hostname == $SWARM_MANAGER]
            restart_policy:
                condition: any
                delay: 5s

    zookeeper2:
        image: hyperledger/fabric-zookeeper:$IMAGE_TAG_3RDP
        hostname: zookeeper2
        networks:
            swarmnet:
                aliases:
                    - zookeeper2.${NETWORK}.foodchain.te-food.com
        volumes:
            - ${DATA}/orderer/zookeeper2/data:/data
            - ${DATA}/orderer/zookeeper2/datalog:/datalog
        environment:
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${NETWORK}
            - ZOO_MY_ID=2
            - ZOO_SERVERS=server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
        deploy:                                                                                                                                                                                                 
            replicas: 1
            placement:
                constraints: [node.hostname == $SWARM_MANAGER]
            restart_policy:
                condition: any 
                delay: 5s
                                                                                                                                                                                                                
    zookeeper3:
        image: hyperledger/fabric-zookeeper:$IMAGE_TAG_3RDP
        hostname: zookeeper3
        networks:
            swarmnet:
                aliases:
                    - zookeeper3.${NETWORK}.foodchain.te-food.com
        volumes:
            - ${DATA}/orderer/zookeeper3/data:/data
            - ${DATA}/orderer/zookeeper3/datalog:/datalog
        environment:
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${NETWORK}
            - ZOO_MY_ID=3
            - ZOO_SERVERS=server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
        deploy:                                                                                                                                                                                                 
            replicas: 1
            placement:
                constraints: [node.hostname == $SWARM_MANAGER]
            restart_policy:
                condition: any 
                delay: 5s
 
